### ISSUE TITLE
Add hacs.json that the integration can be installed via hacs

### ISSUE THREAD

**Issue by Bascht74** [4cc8783b/hass-jarolift#1]
Hi there, 

thank you for changing the integration so that it still works with the newer HA versions...

I am looking into a way to do this via ESPHome but so far I am not successful because of my programming skills. 
I found some references to the keeloq code and there is a possibility to "hack" a Sonoff RF bridge to be used by ESPHOME so that you can send raw RF data like the integration does with the broadcom remote. 
Maybe some day....

But back to this entry: 
It would be nice if you could add a hacs.json file to the repository so that the integration can be installed and upgraded via HACS. see: https://hacs.xyz/docs/publish/start
Just a hacs.json file with
```
{
  "name": "Jarolift",
  "render_readme": true,
  "homeassistant": "2022.02.0"
}

```
would be enough...

**Comment by 4cc8783b** [comment]
Should be done with https://github.com/4cc8783b/hass-jarolift/pull/4
