### ISSUE TITLE
Counter file for all shutters

### ISSUE THREAD

**Issue by Bascht74** [4cc8783b/hass-jarolift#2]
Hi, 

I know that you are not sure if you can fix stuff. 
But at least it should be noted that the counter file ist built for all shutters. That could lead to problems, that the command must be sent 2 times (and with the next counter second time). So you must press the button / send the command twice. 

It would be better if the counter file is built for every serial. Every remote has it's own counter in real life. The counter of the remote and the jarolift shutter must not be too far away.
A solution would be to add the serial to the file name or save multiple lines in the file with the counters of all serials.

**Comment by 4cc8783b** [comment]
Should be fixed with https://github.com/4cc8783b/hass-jarolift/pull/4
