### ISSUE TITLE
Command sometimes not executed

### ISSUE THREAD

**Issue by Bascht74** [4cc8783b/hass-jarolift#3]
The command is send to remote once and `num_repeats` ist not set (I don't know if this is possible here). 

Because other devices are transmitting, too, every command should be send a couple of times, maybe 6-10 times. That way the cover has a better chance to receive one without interference. 

Maybe you could add the num_repeats in the service calls oder execute the service call a couple of times. (Just repeat the sequence, no new counter needed).

**Comment by Bascht74** [comment]
change from
```
            "send_command",
            {"entity_id": remote_entity_id, "command": [packet]},
```
to:
```
            "send_command",
            {"entity_id": remote_entity_id, "command": [packet], "num_repeats": 10},
```
seems to be enough.

**Comment by 4cc8783b** [comment]
Is addressed with https://github.com/4cc8783b/hass-jarolift/pull/4 although I feel like changing the repetition from a loop to your proposed solution.
